# Generated by Django 4.0.4 on 2022-05-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=8)),
                ('nom', models.CharField(max_length=30)),
                ('cognom', models.CharField(max_length=30)),
                ('DataNaix', models.DateField()),
                ('Telefon', models.CharField(max_length=9)),
                ('direccio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PagementDomiciliat', models.BooleanField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personatemplate')),
            ],
        ),
    ]
