# Generated by Django 4.0.4 on 2022-05-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_entrenador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='template',
            new_name='template3',
        ),
        migrations.RenameField(
            model_name='personal',
            old_name='template',
            new_name='template2',
        ),
    ]
