# Generated by Django 4.0.4 on 2022-05-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_rename_template_entrenador_template3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='template2',
        ),
        migrations.DeleteModel(
            name='Entrenador',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
