# Generated by Django 4.0.4 on 2022-05-09 11:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_remove_personal_template2_delete_entrenador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personatemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumFederacio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.personatemplate')),
            ],
        ),
    ]
