# Generated by Django 4.0.4 on 2022-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaTemplate',
            fields=[
                ('DNI', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('cognom', models.CharField(max_length=30)),
                ('DataNaix', models.DateField()),
                ('Telefon', models.CharField(max_length=9)),
                ('direccio', models.CharField(max_length=50)),
            ],
        ),
    ]
