# Generated by Django 4.0.4 on 2022-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('IBAN', models.CharField(max_length=34, primary_key=True, serialize=False)),
            ],
        ),
    ]
