# Generated by Django 4.0.4 on 2022-05-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='classes',
            field=models.ManyToManyField(blank=True, to='club.classe'),
        ),
    ]
