# Generated by Django 4.0.4 on 2022-05-09 12:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenador',
            old_name='NumFederacio',
            new_name='numFederacio',
        ),
        migrations.CreateModel(
            name='SolicitudFederacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('pagament', models.BooleanField()),
                ('concedida', models.BooleanField()),
                ('data', models.DateField()),
                ('numFederacio', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('dataCaducitat', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.client')),
            ],
        ),
    ]
