# Generated by Django 4.0.4 on 2022-05-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_rename_numfederacio_entrenador_numfederacio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudfederacio',
            name='dataCaducitat',
            field=models.DateField(null=True),
        ),
    ]
