# Generated by Django 4.0.4 on 2022-05-09 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PagementDomiciliat', models.BooleanField()),
                ('compteIBAN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.compte')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate')),
            ],
        ),
    ]
