# Generated by Django 4.0.4 on 2022-05-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compteIBAN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.compte')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate')),
            ],
        ),
    ]
