# Generated by Django 4.0.4 on 2022-05-09 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_solicitudfederacio_datacaducitat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudfederacio',
            name='dataCaducitat',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudfederacio',
            name='numFederacio',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(99999999999999)]),
        ),
    ]
