# Generated by Django 4.0.4 on 2022-05-09 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcio',
            fields=[
                ('numInscripcio', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('tipus', models.PositiveSmallIntegerField(choices=[(1, 'Complet'), (2, 'Fitness'), (3, 'Matins')])),
                ('dataInscripcio', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate')),
            ],
        ),
    ]
