# Generated by Django 4.0.4 on 2022-05-09 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_solicitudfederacio_datacaducitat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudfederacio',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate'),
        ),
    ]
