# Generated by Django 4.0.4 on 2022-05-09 16:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_inscripcio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFederacio', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('compteIBAN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.compte')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate')),
            ],
        ),
    ]
