# Generated by Django 4.0.4 on 2022-05-09 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_entrenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudFederacio',
            fields=[
                ('numero', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pagament', models.BooleanField()),
                ('concedida', models.BooleanField()),
                ('data', models.DateField()),
                ('numFederacio', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MaxValueValidator(99999999999999)])),
                ('dataCaducitat', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate')),
            ],
        ),
    ]
