# Generated by Django 4.0.4 on 2022-05-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_solicitudfederacio'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricPagaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('Pagament', models.IntegerField()),
                ('numInscripcio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.inscripcio')),
            ],
            options={
                'unique_together': {('numInscripcio', 'data')},
            },
        ),
    ]
