# Generated by Django 4.0.4 on 2022-05-10 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_historicpagaments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horari',
            fields=[
                ('data', models.DateField(primary_key=True, serialize=False)),
                ('horario', models.TimeField()),
                ('entrenadores', models.ManyToManyField(to='club.entrenador')),
            ],
            options={
                'unique_together': {('horario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='Faltes',
            fields=[
                ('dataFalta', models.DateField(primary_key=True, serialize=False)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personatemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalitat', models.PositiveSmallIntegerField(choices=[(1, 'Boxa'), (2, 'Thai'), (3, 'MMA')])),
                ('tipus', models.PositiveSmallIntegerField(choices=[(1, 'Físic'), (2, 'Técnic'), (3, 'Contacte')])),
                ('realitzada', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.entrenador')),
                ('horari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.horari')),
            ],
            options={
                'unique_together': {('horari', 'coach')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='classes',
            field=models.ManyToManyField(to='club.classe'),
        ),
    ]
